#!/usr/bin/env bash
# 12-tell_the_story_of_passwd

while IFS=: read -r USERNAME PASSWORD USER_ID GROUP_ID USER_INFO HOME_DIRECTORY SHELL
do
echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_INFO"

done < /etc/passwd
