#!/usr/bin/env bash
# The command is going to output numbers from 1 to 20

i=1
while [ "$i" -le 20 ]
do

case "$i" in

4)
echo "$i"
echo "bad luck from china" ;;

9)
echo "$i"
echo "bad luck from Japan" ;;

17)
echo "$i"
echo "bad luck from Italy" ;;

*)
echo "$i" ;;

esac
i=$((i+1))

done
