#!/usr/bin/env bash
# Bash (init) script that manages manage_my_process.

PID="/var/run/my_process.pid"
process="./manage_my_process"

case "$1" in
start)

	"$process" & 
	echo $! | sudo tee "$PID" > /dev/null
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f "$PID" ]; then
          sudo kill "$(cat "$PID")"
          sudo rm -f "$PID"
        fi
        echo "manage_my_process stopped"
        ;;
    restart)
        if [ -f "$PID" ]; then
           sudo kill "$(cat "$PID")"
           sudo rm -f "$PID"
        fi
       "$process" &
        echo $! | sudo tee "$PID" > /dev/null
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
