#!/usr/bin/env bash
# Finding all PIDs of the running 4-to_infinity_and_beyond process

pids=$(pgrep -f 4-to_infinity_and_beyond)

# Check if any PID was found 
if [ -n "$pids" ]; then
echo "Stopping 4-to_infinity_and_beyond process: $pids"
kill $pids

else

echo "No running 4-to_infinity_and_beyond process found"

fi
