#!/bin/bash
# This script displays "To infinity and beyond" indefinitely
# It also displays "I am invincible!!!" inbetween each iteration

while true 
do
eecho "To infinity and beyind"
sleep 2
trap "echo
