#!/bin/bash
# This script displays "To infinity and beyond" indefinitely
# It also displays "I am invincible!!!" inbetween each iteration

while true 
do
echo "To infinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
done
